default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      scheme: "LoanTrack"  # replace with your scheme
    )
    upload_to_testflight(
      api_key: app_store_connect_api_key
    )
  end

  private_lane :app_store_connect_api_key do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )
  end
end
