default_platform(:ios)

platform :ios do
  desc "Build and run tests"
  lane :ci_build do
    clean_build_artifacts
    build_app(
      scheme: "LoanTrack"
    )
    run_tests(
      scheme: "LoanTrack"
    )
  end
end
